services/strongbox/strongbox/config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  root 'static_pages#home'

  # Static
  match '/index', to: 'static_pages#home', via: 'get'

  match '/strongbox/', to: 'static_pages#type', via: 'get'

  # User
  resources :users, only: [:new, :create, :show]
  match '/signup', to: 'users#new', via: 'get'

  #Auth
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  #Items
  resources :items, only: [:create, :destroy, :edit, :update, :show]

  #Checkroom
  resources :checkrooms, only: [:new, :create, :show]
  match '/checkrooms/:id', to: 'checkrooms#show', via: 'post'
end

services/strongbox/strongbox/app/models/checkroom.rb
class Checkroom < ActiveRecord::Base
  validates :name, presence: true, length: {maximum: 255}
  validates :title, presence: true, length: {maximum: 255}
  validates :content, presence: true
  validates :secret, presence: true, length: {maximum: 30, message: "^is too long (maximum is 8 characters)"}
end

services/strongbox/strongbox/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true

  validates :title, presence: true, length: {maximum: 255}
  validates :content, presence: true
end

services/strongbox/strongbox/app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  has_secure_password
  before_save { email.downcase! }
  before_create :create_remember_token

  validates :name, presence: true, length: {maximum: 255}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}

  validates :password, presence: true, length: {minimum: 6}

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

services/strongbox/strongbox/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

services/strongbox/strongbox/app/controllers/checkrooms_controller.rb
class CheckroomsController < ApplicationController
  def new
    @checkroom = Checkroom.new
  end

  def create
    secret = checkroom_params['secret']
    salt = SecureRandom.urlsafe_base64
    random_number = Random.new.rand(5..15)
    checkroom_params['secret'] = salt[0..random_number] + secret +salt[random_number+1..-1]
    @checkroom = Checkroom.new(checkroom_params)
    if @checkroom.save
      flash[:success] = "Checkroom create!"
      redirect_to checkroom_path(@checkroom)
    else
      render 'new'
    end
  end

  def show
    @checkroom = Checkroom.find(params[:id])
    if check_secret
      render 'show'
    else
      render 'login'
    end
  end

  private

  def checkroom_params
    if params.require(:checkroom).kind_of?(Array)
      params.require(:checkroom).map do |u|
        ActionController::Parameters.new(u.to_hash).permit!
      end
    else
      params.require(:checkroom).permit!
    end
  end

  def check_secret
    unless params[:secret].nil?
      if params[:secret].length == (@checkroom['secret'].length - 22)
        return @checkroom.secret.scan(params[:secret]).size
      end
    end
    false
  end

end

services/strongbox/strongbox/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy, :update, :edit, :show]
  before_action :correct_user, only: [:destroy, :update, :edit, :show]

  def show
  end

  def edit
  end

  def create
    item_param = item_params
    item_param['user_id'] = current_user.id

    @item = Item.create(item_param)
    if @item.save
      flash[:success] = 'Thing created!'
      redirect_to @item
    else
      render 'static_pages/home'
    end
  end

  def update
    @id = params[:id].scan /\w/
    @item = Item.update(@id, item_params)
    if !(@item.nil?)
      flash[:success] = 'Thing update!'
      redirect_to @item
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @item = Item.find_by(id: params[:id])
    @item.destroy
    redirect_to root_url
  end

  private

  def correct_user
    @item = Item.find(params[:id])
    redirect_to '/strongbox?type=private' unless current_user?(@item.user)
  end

  def item_params
    if params.require(:item).kind_of?(Array)
      params.require(:item).map do |u|
        ActionController::Parameters.new(u.to_hash).permit!
      end
    else
      params.require(:item).permit!
    end
  end
end

services/strongbox/strongbox/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render 'new'
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

services/strongbox/strongbox/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def type
    @ren = true
    if !params[:type].nil?
      if params[:type] == 'private'
        if signed_in?
          @items = Item.where(user_id: current_user.id).all
          @item_new = Item.new
        else
          store_location
          @ren = false
        end
      elsif params[:type] == 'public'
        @items = Checkroom.all
        @item_new = Checkroom.new
      end
      if @ren
        render params[:type]
      else
        redirect_to signin_url, notice: "Please sign in."
      end
    else
      redirect_to root_path
    end

  end
end

services/strongbox/strongbox/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:show]
  before_action :correct_user, only: [:show]

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    if params.require(:user).kind_of?(Array)
      params.require(:user).map do |u|
        ActionController::Parameters.new(u.to_hash).permit!
      end
    else
      params.require(:user).permit!
    end
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

services/strongbox/strongbox/app/helpers/application_helper.rb
module ApplicationHelper
end

services/strongbox/strongbox/app/helpers/checkrooms_helper.rb
module CheckroomsHelper
end

services/strongbox/strongbox/app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

services/strongbox/strongbox/app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

services/strongbox/strongbox/app/helpers/users_helper.rb
module UsersHelper
end

services/strongbox/strongbox/app/views/checkrooms/login.html.erb
<% provide(:title, 'Secret form') %>

<div class="row">
  <div class="col-md-12">
    <h1>Open checkroom</h1>
    <%= form_tag(checkroom_path) do %>
        <div class="form-group">
          <%= password_field_tag :secret, nil, placeholder: "Secret", class: "form-control" %>
        </div>
        <%= submit_tag "View", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

services/strongbox/strongbox/app/views/checkrooms/new.html.erb
<% provide(:title, 'New checkroom') %>

<div class="row">
  <div class="col-md-12">
    <h1>New checkroom</h1>
    <%= form_for(@checkroom) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.text_field :name, placeholder: "Name checkroom", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.text_area :content, placeholder: "Description", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.password_field :secret, placeholder: "Secret", class: "form-control" %>
        </div>
        <%= f.submit "Add", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

services/strongbox/strongbox/app/views/checkrooms/show.html.erb
<div class="row">
  <div class="col-md-6 checkroom">
    <h2 class="checkroom__name"><%= @checkroom.name %></h2>
    <h3 class="checkroom__title"><%= @checkroom.title %></h3>
    <p class="checkroom__content"><%= @checkroom.content %></p>
  </div>
</div>

services/strongbox/strongbox/app/views/items/edit.html.erb
<% provide(:title, @item.title) %>
<div class="row">
  <div class="col-md-12">

    <%= form_for(@item) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.text_field :title, placeholder: "Title", class: "form-control", name: 'item[][title]' %>
        </div>
        <div class="form-group">
          <%= f.text_area :content, placeholder: "Description", class: "form-control", name: 'item[][content]' %>
        </div>
        <%= f.submit "Save", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

services/strongbox/strongbox/app/views/items/show.html.erb
<% provide(:title, @item.title) %>
<div class="row">
  <div class="col-md-12">
    <section class="item">
      <h1 class="item__title">
        <%= @item.title %>
      </h1>
      <p class="item__contetn">
        <%= @item.content %>
      </p>
      <%= link_to "Edit", edit_item_path(@item) %>
    </section>
  </div>
</div>

services/strongbox/strongbox/app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="text-muted"> Place sticky footer content here.</p>
  </div>
</div>

services/strongbox/strongbox/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Strongbox", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <% if signed_in? %>
            <li><%= link_to "Profile", current_user %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
            <li><%= link_to signout_path, method: "delete" do %>
                  <%= fa_icon "lock" %>  Sign out
              <% end %>
            </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

services/strongbox/strongbox/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <%= yield %>
</div>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

services/strongbox/strongbox/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

services/strongbox/strongbox/app/views/shared/_item_form.html.erb
<%= form_for(@item_new) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.text_area :content, placeholder: "Description", class: "form-control" %>
    </div>
    <%= f.submit "Add", class: "btn btn-large btn-primary" %>
<% end %>

services/strongbox/strongbox/app/views/static_pages/home.html.erb
<div style="display: flex;justify-content: space-around;">
  <div style="display: flex;flex-direction: row;justify-content:center;align-items:center;">
    <a href="/strongbox?type=public" class="btn btn-large btn-primary">Checkroom</a>
  </div>
  <div style="display: flex;flex-direction: row;justify-content:center;align-items:center;">
    <a href="/strongbox?type=private" class="btn btn-large btn-primary">My strongbox</a>
  </div>
</div>

services/strongbox/strongbox/app/views/static_pages/private.html.erb
<div class="row">
  <div class="col-md-12">
    <% unless @items.nil? %>
        <h1>List your items:</h1>
        <ul>
          <% @items.each do |item| %>
              <li> <%= link_to item.title, item_path(item) %><br/></li>
          <% end %>
        </ul>
    <% end %>
    <h2>Add item</h2>
    <%= render 'shared/item_form' %>
  </div>
</div>

services/strongbox/strongbox/app/views/static_pages/public.html.erb
<div class="row">
  <div class="col-md-12">
    <div>
      <% unless @items.nil? %>
          <h1>Public strongbox:</h1>
          <ul class="image-list">
            <% @items.each do |item| %>
                <li class="image-list__item">
                  <a class="fancyimage" rel="group">
                    <div class="image-list__item--block">
                      <%= image_tag "locker-luggage.jpg", class: "image-list__item-img", style: "height: 150px;"%>
                    </div>
                  </a>
                  <%= link_to item.name, checkroom_path(item) %>
                </li>
            <% end %>
          </ul>
      <% end %></div>
    <%= link_to "Add checkroom", new_checkroom_path %>
  </div>
</div>

services/strongbox/strongbox/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col-md-8">
  </div>
  <div class="col-md-4">
    <h1>Sign up</h1>

    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>

        <%= f.submit "Create my account", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

services/strongbox/strongbox/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section class="users">
      <h1 class="users__name">
        <%= @user.name %>
      </h1>
      <%= @user.email %>
    </section>
  </aside>
</div>